version: "3.7"

services:
  node:
      image: continuumio/anaconda3
      command: "
        jupyter notebook --port=8887 --no-browser --ip=0.0.0.0 --allow-root "
      volumes:
        - ./data:/data
      ports:
        - 8887:8887
